# Generated by Django 5.0.4 on 2024-05-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_alter_quiz_options_quiz_owner_unit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mcq.question'),
        ),
    ]
