# Generated by Django 5.0.4 on 2024-04-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_choice_slug_feedback_slug_question_slug_quiz_slug_and_more'),
    ]

    operations = [
    ]
