# Generated by Django 5.0.4 on 2024-04-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_auto_20240423_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='paper_type',
            field=models.CharField(choices=[('EOR', 'End of Rotation'), ('EOY', 'End of Year')], default='EOR', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.unit'), max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year_tested',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='year'),
        ),
    ]
