# Generated by Django 5.0.4 on 2024-04-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_quiz_paper_type_quiz_tags_quiz_year_tested'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
    ]
