# Generated by Django 5.0.4 on 2024-05-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_alter_feedback_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='year_tested',
            new_name='year',
        ),
    ]
