# Generated by Django 5.0.4 on 2024-04-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_alter_choice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='related_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_quizzes', to='mcq.unit'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='related_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_qustions', to='mcq.unit'),
        ),
    ]
