# Generated by Django 5.0.4 on 2024-05-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_rename_year_tested_quiz_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='year',
            new_name='year_tested',
        ),
    ]
