# Generated by Django 5.0.4 on 2024-06-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_rename_year_quiz_year_tested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='year_tested',
            new_name='year',
        ),
    ]
