# Generated by Django 5.0.4 on 2024-04-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_question_related_topic_quiz_related_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tags',
        ),
    ]
