# Generated by Django 5.0.4 on 2024-06-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0007_rename_year_tested_quiz_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='related_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_questions', to='mcq.unit'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='year'),
        ),
    ]
