# Generated by Django 5.0.4 on 2024-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_graduation_year_user_institution_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(default=2024),
        ),
    ]
